/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.Controlador_FRM_RegistroUsuarios;
import java.awt.event.ActionListener;

import javax.swing.JOptionPane;

/**
 *
 * @author chelvivil
 */
public class FRM_RegistroUsuario extends javax.swing.JFrame {

    /**
     * Creates new form FRM_RegistroUsuario
     */
    Controlador_FRM_RegistroUsuarios controlador_FRM_RegistroUsuarios;

    public FRM_RegistroUsuario(FRM_MenuPrincipal control)//MetodoConstructor
    {
        initComponents();
          this.setLocation(310, 130);
        controlador_FRM_RegistroUsuarios = new Controlador_FRM_RegistroUsuarios(this, control);

        gUI_Botones1.agregarEventos(controlador_FRM_RegistroUsuarios);
        gUI_Botones1.estadoInicial();//********************************************************
        agregarEvento();
    }

    public void habilitarAgregar(){
    gUI_Botones1.habilitarAgregar();
    }
    public void habilitarBotones()
    {
        gUI_Botones1.habilitarBotones();
    }
    public void limpiarInterfaz()
    {
   //this.jt_Usuario.setText("");
   this.jt_Cedula.setText("");
   this.jt_Nombre.setText("");
   this.jtp_Password.setText("");
    }
    
    public void agregarEvento()//*************************
    {
    this.jbtn_ConsultaRapida.addActionListener(controlador_FRM_RegistroUsuarios);
    }
    public String[] devolverInformacion() {
        String arreglo[];
        arreglo = new String[4];
        arreglo[0] = jt_Cedula.getText();
        arreglo[1] = jt_Nombre.getText();
        arreglo[2] = jt_Usuario.getText();
        arreglo[3] = jtp_Password.getText();
        return arreglo;
    }

    public String[] devolverInformacionVersion2() {
        String arreglo[];
        arreglo = new String[4];
        arreglo[0] = jt_Usuario.getText();
        arreglo[1] = jt_Nombre.getText();
        arreglo[2] = jtp_Password.getText();
        arreglo[3] = jt_Cedula.getText();
        return arreglo;
    }

    public void mostrarInformacion(String arreglo[]) {
        this.jt_Cedula.setText(arreglo[1]);
        this.jt_Nombre.setText(arreglo[0]);
       // this.jt_Usuario.setText(arreglo[2]);
        this.jtp_Password.setText(arreglo[2]);

    }

    public void mostrarInformacionArchivoUsuario(String arreglo[]) {
        this.jt_Nombre.setText(arreglo[0]);
        this.jtp_Password.setText(arreglo[1]);
        this.jt_Cedula.setText(arreglo[2]);
    }

    public String devolverUsuario() {
        return this.jt_Usuario.getText();
    }

    public String devolverCedula() {
        return this.jt_Cedula.getText();
    }

    public void mostrarMensaje(String mensaje) {
        JOptionPane.showMessageDialog(null, mensaje);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jt_Cedula = new javax.swing.JTextField();
        jt_Nombre = new javax.swing.JTextField();
        jt_Usuario = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        gUI_Botones1 = new Vista.GUI_Botones();
        jbtn_ConsultaRapida = new javax.swing.JButton();
        jbtn_ConsultaRapida1 = new javax.swing.JButton();
        jtp_Password = new javax.swing.JPasswordField();

        setMinimumSize(new java.awt.Dimension(470, 350));
        setPreferredSize(new java.awt.Dimension(420, 269));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Cedula");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Nombre");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Usuario");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));
        getContentPane().add(jt_Cedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 200, -1));
        getContentPane().add(jt_Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 200, -1));
        getContentPane().add(jt_Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 130, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Contraseña");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        gUI_Botones1.setOpaque(false);
        getContentPane().add(gUI_Botones1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, -1, -1));

        jbtn_ConsultaRapida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buscar.png"))); // NOI18N
        jbtn_ConsultaRapida.setActionCommand("consultaRapida");
        getContentPane().add(jbtn_ConsultaRapida, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 40, -1, -1));

        jbtn_ConsultaRapida1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buscar.png"))); // NOI18N
        jbtn_ConsultaRapida1.setActionCommand("consultaRapida");
        getContentPane().add(jbtn_ConsultaRapida1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 40, -1, -1));
        getContentPane().add(jtp_Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 200, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Vista.GUI_Botones gUI_Botones1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton jbtn_ConsultaRapida;
    private javax.swing.JButton jbtn_ConsultaRapida1;
    private javax.swing.JTextField jt_Cedula;
    private javax.swing.JTextField jt_Nombre;
    private javax.swing.JTextField jt_Usuario;
    private javax.swing.JPasswordField jtp_Password;
    // End of variables declaration//GEN-END:variables
}
