/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.Controlador_FRM_FuenteSistema;
import java.awt.event.ActionListener;

/**
 *
 * @author Leandro
 */
public class FRM_FuenteSistema extends javax.swing.JFrame 
{

    /**
     * Creates new form FRM_SeleccionarTipo
     */
    Controlador_FRM_FuenteSistema controlador_FRM_FuenteSistema;
    private String valorFuente = "";

    public FRM_FuenteSistema()//METODO CONSTRUCTOR
    {
        initComponents();
        setLocation(300, 100);//locacion
        controlador_FRM_FuenteSistema = new Controlador_FRM_FuenteSistema(this);//Mando por parametro la clase al controlador
        agregarEventos(controlador_FRM_FuenteSistema);//Escuchado
    }

    public void agregarEventos(ActionListener controlador) {
        this.jbtn_Entrar.addActionListener(controlador);

    }

    public String setValorFuenteSistema() {
        if (this.jrbt_BasesDeDatos.isSelected())//Escuchaseleccion
        {
            valorFuente = "" + 3;

        } else if (this.jrbt_Xml.isSelected()) //Escuchaseleccion
        {
            valorFuente = "" + 2;

        }
        if (this.jrbt_ArchivosPlanos.isSelected())//Escuchaseleccion 
        {
            valorFuente = "" + 1;

        }

        return valorFuente;

    }

 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jrbt_ArchivosPlanos = new javax.swing.JRadioButton();
        jrbt_Xml = new javax.swing.JRadioButton();
        jrbt_BasesDeDatos = new javax.swing.JRadioButton();
        jbtn_Entrar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(760, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonGroup1.add(jrbt_ArchivosPlanos);
        jrbt_ArchivosPlanos.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jrbt_ArchivosPlanos.setText("Archivos Planos");
        jrbt_ArchivosPlanos.setActionCommand("ArchivosPlanos");
        jrbt_ArchivosPlanos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbt_ArchivosPlanosActionPerformed(evt);
            }
        });
        getContentPane().add(jrbt_ArchivosPlanos, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 280, -1, -1));

        buttonGroup1.add(jrbt_Xml);
        jrbt_Xml.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jrbt_Xml.setText("XML");
        jrbt_Xml.setActionCommand("Xml");
        jrbt_Xml.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbt_XmlActionPerformed(evt);
            }
        });
        getContentPane().add(jrbt_Xml, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 180, -1, -1));

        buttonGroup1.add(jrbt_BasesDeDatos);
        jrbt_BasesDeDatos.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jrbt_BasesDeDatos.setText("Bases de Datos");
        jrbt_BasesDeDatos.setActionCommand("BasesDeDatos");
        jrbt_BasesDeDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbt_BasesDeDatosActionPerformed(evt);
            }
        });
        getContentPane().add(jrbt_BasesDeDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 230, -1, -1));

        jbtn_Entrar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbtn_Entrar.setText("Entrar");
        jbtn_Entrar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(153, 153, 255), java.awt.Color.darkGray, java.awt.Color.darkGray));
        getContentPane().add(jbtn_Entrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, 100, 40));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Seleccione la Fuente de Trabajo");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 250, 40));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Bienvenido Al Sistema De Ematrícula");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Estudiante Mujer.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jrbt_ArchivosPlanosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbt_ArchivosPlanosActionPerformed
        
    }//GEN-LAST:event_jrbt_ArchivosPlanosActionPerformed

    private void jrbt_XmlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbt_XmlActionPerformed
       
    }//GEN-LAST:event_jrbt_XmlActionPerformed

    private void jrbt_BasesDeDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbt_BasesDeDatosActionPerformed
       
    }//GEN-LAST:event_jrbt_BasesDeDatosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) //MAIN DE PROYECTO
    {
        
        java.awt.EventQueue.invokeLater(new Runnable() 
        {
            public void run()
            {
                new FRM_FuenteSistema().setVisible(true);
        
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton jbtn_Entrar;
    private javax.swing.JRadioButton jrbt_ArchivosPlanos;
    private javax.swing.JRadioButton jrbt_BasesDeDatos;
    private javax.swing.JRadioButton jrbt_Xml;
    // End of variables declaration//GEN-END:variables

}
