/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.Controlador_FRM_MantenimientoCursos;
import javax.swing.JOptionPane;

/**
 *
 * @author Leandro
 */
public class FRM_RegistroCursos extends javax.swing.JFrame {

    /**
     * Creates new form FRM_MantenimientoCursos
     */
    public Controlador_FRM_MantenimientoCursos controlador_FRM_MantenimientoCursos;

    public FRM_RegistroCursos(FRM_MenuPrincipal control) {
        initComponents();
        this.setLocation(310, 130);
        controlador_FRM_MantenimientoCursos = new Controlador_FRM_MantenimientoCursos(this, control);
        this.gUI_Botones1.agregarEventos(controlador_FRM_MantenimientoCursos);
        gUI_InformacionCursos1.agregarEvento(controlador_FRM_MantenimientoCursos);
        gUI_Botones1.estadoInicial();

    }

    public void mostrarMensaje(String mensaje) {
        JOptionPane.showMessageDialog(null, mensaje);
    }

    public String[] devolverInformacion() {
        return this.gUI_InformacionCursos1.devolverInformacion();
    }

    public String devolverSigla() {
        return this.gUI_InformacionCursos1.devolverSigla();
    }

    public void mostrarInformacion(String arreglo[]) {
        this.gUI_InformacionCursos1.mostrarInformacion(arreglo);
    }

    public void mostrarInformacionXML(String arreglo[]) {
        this.gUI_InformacionCursos1.mostrarInformacionXML(arreglo);
    }

    public void habilitarAgregar() {
        this.gUI_Botones1.habilitarAgregar();
        this.gUI_InformacionCursos1.habilitarOpciones();

    }

    public void habilitarOpciones() {
        this.gUI_Botones1.habilitarOpciones();
        this.gUI_InformacionCursos1.habilitarOpciones();

    }

    public void habilitarBotones() {
        gUI_Botones1.habilitarBotones();
    }

    public void desahabilitarSigla() {
        this.gUI_InformacionCursos1.desahabilitarSigla();
    }

    public void limpiarInterfaz() {

        this.gUI_InformacionCursos1.limpiarInterfaz();
    }

    public void estadoInicial() {
        this.gUI_InformacionCursos1.estadoInicial();
        this.gUI_Botones1.estadoInicial();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gUI_InformacionCursos1 = new Vista.GUI_InformacionCursos();
        gUI_Botones1 = new Vista.GUI_Botones();

        setMinimumSize(new java.awt.Dimension(400, 350));
        setPreferredSize(new java.awt.Dimension(285, 275));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        gUI_InformacionCursos1.setOpaque(false);
        getContentPane().add(gUI_InformacionCursos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        gUI_Botones1.setOpaque(false);
        getContentPane().add(gUI_Botones1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Vista.GUI_Botones gUI_Botones1;
    private Vista.GUI_InformacionCursos gUI_InformacionCursos1;
    // End of variables declaration//GEN-END:variables
}
