/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.Controlador_FRM_MantenimientoEstudiantes;
import javax.swing.JOptionPane;

/**
 *
 * @author Leandro
 */
public class FRM_RegistroEstudiantes extends javax.swing.JFrame {

    public Controlador_FRM_MantenimientoEstudiantes controlador_FRM_MantenimientoEstudiantes;

    public FRM_RegistroEstudiantes(FRM_MenuPrincipal control) {
        initComponents();
        this.setLocation(310, 130);

        controlador_FRM_MantenimientoEstudiantes = new Controlador_FRM_MantenimientoEstudiantes(this, control);

        gUI_Botones1.agregarEventos(controlador_FRM_MantenimientoEstudiantes);
        gUI_InformacionEstudiantes1.agregarEventos(controlador_FRM_MantenimientoEstudiantes);
        gUI_Botones1.estadoInicial();//**************************

    }

    public void habilitarAgregar() {
        gUI_Botones1.habilitarAgregar();
    }

    public void habilitarBotones() {
        gUI_Botones1.habilitarBotones();
    }

    public void mostrarMensaje(String mensaje) {
        JOptionPane.showMessageDialog(null, mensaje);
    }

    public String[] devolverInformacion() {
        return this.gUI_InformacionEstudiantes1.devolverInformacion();
    }

      public void habilitarTodo()
      {
         this.gUI_Botones1.habilitarTodo();
       }
      
    public String devolverCedula() {
        return this.gUI_InformacionEstudiantes1.devolverCedula();

    }

    public void mostrarInformacionXML(String arreglo[]) {

        this.gUI_InformacionEstudiantes1.mostrarInformacionXML(arreglo);

    }

    public void mostrarInformacion(String arreglo[]) {

        this.gUI_InformacionEstudiantes1.mostrarInformacion(arreglo);

    }

   
    public void habilitarOpciones() 
    {
        this.gUI_Botones1.habilitarOpciones();
        this.gUI_InformacionEstudiantes1.habilitarOpciones();

    }

    public void desahabilitarCedula() {
        this.gUI_InformacionEstudiantes1.desahabilitarCedula();
    }

    public void limpiarInterfaz() {

        this.gUI_InformacionEstudiantes1.limpiarInterfaz();
    }

    public void estadoInicial() {
        this.gUI_InformacionEstudiantes1.estadoInicial();
        this.gUI_Botones1.estadoInicial();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gUI_Botones1 = new Vista.GUI_Botones();
        gUI_InformacionEstudiantes1 = new Vista.GUI_InformacionEstudiantes();
        jTextField1 = new javax.swing.JTextField();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        gUI_Botones1.setBackground(new java.awt.Color(248, 244, 251));
        getContentPane().add(gUI_Botones1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, -1, -1));

        gUI_InformacionEstudiantes1.setBackground(new java.awt.Color(248, 244, 251));
        getContentPane().add(gUI_InformacionEstudiantes1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 410, -1));

        jTextField1.setBackground(new java.awt.Color(248, 244, 251));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 270));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Vista.GUI_Botones gUI_Botones1;
    private Vista.GUI_InformacionEstudiantes gUI_InformacionEstudiantes1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
