/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.Controlador_FRM_MenuPrincipal;
import Modelo.MetodosUsuarioArchivos;
import ModeloConexion.ConexionUsuario;
import javax.swing.JOptionPane;

/** 
 *
 * @author Leandro
 */

public class FRM_MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FRM_MenuPrincipal
     */
    Controlador_FRM_MenuPrincipal controlador_FRM_MenuPrincipal;
    FRM_FuenteSistema fRM_FuenteSistema;
    FRM_LoginUsuario fRM_LoginUsuario;
    MetodosUsuarioArchivos metodosUsuarioArchivos;
    FRM_LoginArchivos fRM_LoginArchivos;
    int valorFuenteSistema = 0;
    ConexionUsuario conexionUsuario;

    public FRM_MenuPrincipal(FRM_FuenteSistema fRM_FuenteSistema) throws Exception 
    {
        
        initComponents();
        this.setLocation(300, 100);
        setVisible(false);
        
        
        controlador_FRM_MenuPrincipal = new Controlador_FRM_MenuPrincipal(this);
        this.fRM_FuenteSistema = fRM_FuenteSistema;

        if (seleccionarFuenteDelSistema()== 3)///Bases de datos
        {
            conexionUsuario=new ConexionUsuario();
            fRM_LoginUsuario = new FRM_LoginUsuario(this);
            
            if (fRM_LoginUsuario.verificarExistenciaDeBasesDedatosUsuarios()) //pregunta si existe usuario en la base de datos
            {
                fRM_LoginUsuario.setVisible(true);
            } else {
                this.setVisible(true);
            
            }
            
        }
       
        
         if (seleccionarFuenteDelSistema()== 1)//Archivos Planos
        {
            metodosUsuarioArchivos = new MetodosUsuarioArchivos();
            fRM_LoginArchivos = new FRM_LoginArchivos(this);
            if (metodosUsuarioArchivos.verificarExistenciaDeArchivoDeUsuarios()) {
                fRM_LoginArchivos.setVisible(true);
                
            } else {
              //  this.setVisible(true);//**************************************************************
            }

        }
         if (seleccionarFuenteDelSistema()== 2)//XML
        {
            //this.setVisible(true);
           
             
               
        }
        seleccionarFuenteDelSistema();
        agregarEventos();
    }//Fin del Metodo constructor...

    public void agregarEventos()//Escuhador de eventos.
    {
        this.jmi_Salir.addActionListener(controlador_FRM_MenuPrincipal);
        this.jmi_Estudiante.addActionListener(controlador_FRM_MenuPrincipal);
        this.jmi_Curso.addActionListener(controlador_FRM_MenuPrincipal);
        this.jmi_Matricula.addActionListener(controlador_FRM_MenuPrincipal);
        this.jmi_Usuario.addActionListener(controlador_FRM_MenuPrincipal);

    }

    public int seleccionarFuenteDelSistema() 
    {
        valorFuenteSistema = Integer.parseInt(fRM_FuenteSistema.setValorFuenteSistema());//LLAMA AL NUMERO GUARDADO EN FRM_FUENTE SISTEMA
        return valorFuenteSistema;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        fondo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jmi_Salir = new javax.swing.JMenuItem();
        jm_registro = new javax.swing.JMenu();
        jmi_Estudiante = new javax.swing.JMenuItem();
        jmi_Curso = new javax.swing.JMenuItem();
        jmi_Matricula = new javax.swing.JMenuItem();
        jm_Usuario = new javax.swing.JMenu();
        jmi_Usuario = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setMinimumSize(new java.awt.Dimension(800, 500));
        setPreferredSize(new java.awt.Dimension(800, 555));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/menuPrincipal.png"))); // NOI18N

        jMenu1.setText("Salir");

        jmi_Salir.setText("Salir");
        jMenu1.add(jmi_Salir);

        jMenuBar1.add(jMenu1);

        jm_registro.setText("Registro");

        jmi_Estudiante.setText("Estudiante");
        jm_registro.add(jmi_Estudiante);

        jmi_Curso.setText("Curso");
        jmi_Curso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_CursoActionPerformed(evt);
            }
        });
        jm_registro.add(jmi_Curso);

        jmi_Matricula.setText("Matricula");
        jm_registro.add(jmi_Matricula);

        jMenuBar1.add(jm_registro);

        jm_Usuario.setText("Usuario");
        jm_Usuario.setActionCommand("MenuUsuario");

        jmi_Usuario.setText("Registrar Usuario");
        jmi_Usuario.setActionCommand("Usuario");
        jm_Usuario.add(jmi_Usuario);

        jMenuBar1.add(jm_Usuario);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.PREFERRED_SIZE, 764, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(fondo)
                .addGap(0, 51, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmi_CursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_CursoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmi_CursoActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel fondo;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenu jm_Usuario;
    private javax.swing.JMenu jm_registro;
    private javax.swing.JMenuItem jmi_Curso;
    private javax.swing.JMenuItem jmi_Estudiante;
    private javax.swing.JMenuItem jmi_Matricula;
    private javax.swing.JMenuItem jmi_Salir;
    private javax.swing.JMenuItem jmi_Usuario;
    // End of variables declaration//GEN-END:variables
}
