package Vista;

import Controlador.Controlador_FRM_LoginArchivos;

import javax.swing.JOptionPane;

public class FRM_LoginArchivos extends javax.swing.JFrame {

    Controlador_FRM_LoginArchivos controlador_FRM_LoginArchivos;
    FRM_MenuPrincipal fRM_MenuPrincipal;
    FRM_RegistroUsuario fRM_RegistroUsuario;

    public FRM_LoginArchivos(FRM_MenuPrincipal principal) throws Exception {
        this.fRM_MenuPrincipal = principal;

        fRM_RegistroUsuario = new FRM_RegistroUsuario(principal);

        initComponents();

        this.setLocation(310, 130);
        controlador_FRM_LoginArchivos = new Controlador_FRM_LoginArchivos(this, principal);
        this.jb_Login.addActionListener(controlador_FRM_LoginArchivos);
    }

    public void hacerLogin() 
    {
        JOptionPane.showMessageDialog(null, "Existen usuarios registrados, Proceda hacer Login");

        this.setVisible(true);

    }

    public void noHacerLogin() {
        JOptionPane.showMessageDialog(null, "NO EXISTE USUARIOS \nPor favor proceda a registrar un Usuario");
        setVisible(false);
        fRM_RegistroUsuario.setVisible(true);

    }

    public void mostrarVentanaLogin() 
    {
        setVisible(false);
        fRM_MenuPrincipal.setVisible(true);
    }

    public void limpiarVentanaLogin() {
        jtp_Password.setText("");
        jt_NombreUsuario.setText("");
    }

    public String getJtNombreUsuario() {
        return this.jt_NombreUsuario.getText();
    }

    public String getJtContrasena() 
    {
        return this.jtp_Password.getText();
    }

    public String devolverNombreUsuario() {
        return jt_NombreUsuario.getText();
    }

    public String devolverContrasena() 
    {
        return jtp_Password.getText();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jt_NombreUsuario = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jb_Login = new javax.swing.JButton();
        jtp_Password = new javax.swing.JPasswordField();

        jTextField1.setBackground(new java.awt.Color(204, 204, 255));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        setMinimumSize(new java.awt.Dimension(400, 270));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Nombre Usuario:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        jt_NombreUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jt_NombreUsuarioKeyPressed(evt);
            }
        });
        getContentPane().add(jt_NombreUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 170, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Contraseña:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        jb_Login.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jb_Login.setText("Entrar");
        jb_Login.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.gray, java.awt.Color.lightGray, java.awt.Color.darkGray, java.awt.Color.darkGray));
        jb_Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_LoginActionPerformed(evt);
            }
        });
        jb_Login.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jb_LoginKeyPressed(evt);
            }
        });
        getContentPane().add(jb_Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 100, 30));
        getContentPane().add(jtp_Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 170, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jt_NombreUsuarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jt_NombreUsuarioKeyPressed


        if (evt.getKeyCode() == 10) {
            controlador_FRM_LoginArchivos.consultarUsuario();

        }

    }//GEN-LAST:event_jt_NombreUsuarioKeyPressed

    private void jb_LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_LoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_LoginActionPerformed

    private void jb_LoginKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jb_LoginKeyPressed

        if (evt.getKeyCode() == 10) {
            controlador_FRM_LoginArchivos.consultarUsuario();

        }
    }//GEN-LAST:event_jb_LoginKeyPressed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton jb_Login;
    private javax.swing.JTextField jt_NombreUsuario;
    private javax.swing.JPasswordField jtp_Password;
    // End of variables declaration//GEN-END:variables
}
