/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author Leandro
 */
import Controlador.Controlador_FRM_MantenimientoEstudiantes;
public class GUI_InformacionEstudiantes extends javax.swing.JPanel 
{
Controlador_FRM_MantenimientoEstudiantes controlador_FRM_MantenimientoEstudiantes;

    /**
     * Creates new form GUI_InformacionEstudiantes
     */
    public GUI_InformacionEstudiantes() 
    {
        initComponents();
       
    }
    
    public void agregarEventos(Controlador_FRM_MantenimientoEstudiantes controlador_FRM_MantenimientoEstudiantes)
    {
        this.controlador_FRM_MantenimientoEstudiantes=controlador_FRM_MantenimientoEstudiantes;
        this.jbtn_ConsultaRapida.addActionListener(controlador_FRM_MantenimientoEstudiantes);
    }
    
    
    public String[] devolverInformacion()
    {
        String arreglo[];
        arreglo=new String[3];
        arreglo[0]=this.jt_Cedula.getText();
        arreglo[1]=this.jt_NombreCompleto.getText();
        arreglo[2]=this.jt_Direccion.getText();
        
        return arreglo;
    }
    public String devolverCedula()
    {
        return this.jt_Cedula.getText();
    }
    public void mostrarInformacion(String arreglo[])
    {
        this.jt_NombreCompleto.setText(arreglo[0]);
        this.jt_Direccion.setText(arreglo[1]);
        
    }
public void mostrarInformacionXML(String arreglo[])
    {
        this.jt_NombreCompleto.setText(arreglo[1]);
        this.jt_Direccion.setText(arreglo[2]);
        
    }
 public void habilitarOpciones()
 {
    this.jt_Direccion.setEnabled(true);
    this.jt_NombreCompleto.setEnabled(true);

    }
     public void limpiarInterfaz(){
    this.jt_Cedula.setText("");
        this.jt_Direccion.setText("");
    this.jt_NombreCompleto.setText("");

    
    }
    
    public void desahabilitarCedula(){
    
    this.jt_Cedula.setEnabled(false);
    
    }
    
    public void estadoInicial(){
    this.jt_Cedula.setEnabled(true);
    this.jt_Direccion.setEnabled(false);
    this.jt_NombreCompleto.setEnabled(false);

            
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jl_Cedula = new javax.swing.JLabel();
        jl_NombreCompleto = new javax.swing.JLabel();
        jl_Direccion = new javax.swing.JLabel();
        jt_Cedula = new javax.swing.JTextField();
        jt_NombreCompleto = new javax.swing.JTextField();
        jt_Direccion = new javax.swing.JTextField();
        jbtn_ConsultaRapida = new javax.swing.JButton();

        jl_Cedula.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jl_Cedula.setText("Cédula");

        jl_NombreCompleto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jl_NombreCompleto.setText("Nombre Completo");

        jl_Direccion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jl_Direccion.setText("Dirección");

        jbtn_ConsultaRapida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buscar.png"))); // NOI18N
        jbtn_ConsultaRapida.setActionCommand("ConsultaRapida");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jl_NombreCompleto)
                    .addComponent(jl_Cedula)
                    .addComponent(jl_Direccion))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jt_NombreCompleto)
                            .addComponent(jt_Direccion, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jt_Cedula, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbtn_ConsultaRapida)
                        .addGap(40, 40, 40))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jl_Cedula, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(jl_NombreCompleto)
                        .addGap(21, 21, 21)
                        .addComponent(jl_Direccion))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(jt_Cedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jbtn_ConsultaRapida))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jt_NombreCompleto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jt_Direccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbtn_ConsultaRapida;
    private javax.swing.JLabel jl_Cedula;
    private javax.swing.JLabel jl_Direccion;
    private javax.swing.JLabel jl_NombreCompleto;
    private javax.swing.JTextField jt_Cedula;
    private javax.swing.JTextField jt_Direccion;
    private javax.swing.JTextField jt_NombreCompleto;
    // End of variables declaration//GEN-END:variables
}
